[project]
name = "pneutrinoutil"
version = "0.8.5"
description = "NEUTRINO util"
readme = "README.md"
requires-python = "==3.14.2"
dependencies = [
    "ansible==13.2.0",
]
dev-dependencies = [
    "yamllint==1.38.0",
]
