dist_dir: "{{ ansible_env.GIT_ROOT }}/dist"
tmp_dir: "{{ dist_dir }}/tmp"
# https://studio-neutrino.com/535/
neutrino_version: v3.0.4
singers:
  - name: "東北きりたん"
    version: v3.0.4
  - name: "東北イタコ"
    version: v3.0.4
  - name: "東北ずん子"
    version: v3.0.4
  - name: "四国めたん"
    version: v3.0.4
  - name: "ずんだもん"
    version: v3.0.4
  - name: "大江戸ちゃんこ"
    version: v3.0.4
  - name: "No.7"
    version: v3.0.4
